#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
curl -fsSL --create-dirs https://raw.github.com/mislav/dotfiles/1500cd2/bin/tmux-vim-select-pane -o \
    ~/lib/bin/tmux-vim-select-pane

rm -f ~/.bash_profile
rm -f ~/.bashrc

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

chmod +x ~/lib/bin/tmux-vim-select-pane
